### ISSUE TITLE
tooltip flashing open and then automatically closing. unable to use

### ISSUE THREAD

**Issue by pixel-wraith** [leo-holanda/changes-counter#4] opened 2023-11-15 21:36 UTC
When clicking on `Changes: ###` in the bottom status bar, I'm seeing the tooltip flash open and then immediately closing. It's happening really fast...it's only open for maybe 100-200 milliseconds.

**Comment by leo-holanda** [comment] 2023-11-16 12:31
Hey @iamthe-Wraith! I tried to reproduce this bug and, sadly, I couldn't. Changing from Linux (Debian 12) to Windows 11 and trying different VS Code versions and repositories didn't trigger it, unfortunately.

It seems that the only expected way for the tooltip to close is by either clicking on the status bar item or moving the cursor away from the tooltip or the item. Since it's kinda strange that clicking on an unclickable item can close its tooltip before it even appears, I will create an issue in the VS Code repository to discuss it with its maintainers.

But, since the extension is unable to be used and it can't continue this way, I thought about a way of dealing with this bug: create an item at the left bar, like the Search and Source Control ones, that shows the same thing as the tooltip. It would be sort of a fallback while the tooltip bug isn't clarified and fixed. It could be optional too if anyone prefers to disable it. What do you think?

**Closed as not planned** 2024-03-11 19:55 UTC
